/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard'
import { Route as AuthenticatedInstructorDashboardRouteImport } from './routes/_authenticated/instructor/dashboard'
import { Route as AuthenticatedInstructorTestsTestIdRouteImport } from './routes/_authenticated/instructor/tests.$testId'
import { Route as AuthenticatedStudentTestsTestIdSubmittedRouteImport } from './routes/_authenticated/student/tests.$testId.submitted'
import { Route as AuthenticatedStudentTestsTestIdStartRouteImport } from './routes/_authenticated/student/tests.$testId.start'
import { Route as AuthenticatedInstructorTestsTestIdResultsRouteImport } from './routes/_authenticated/instructor/tests.$testId.results'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorDashboardRoute =
  AuthenticatedInstructorDashboardRouteImport.update({
    id: '/instructor/dashboard',
    path: '/instructor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorTestsTestIdRoute =
  AuthenticatedInstructorTestsTestIdRouteImport.update({
    id: '/instructor/tests/$testId',
    path: '/instructor/tests/$testId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentTestsTestIdSubmittedRoute =
  AuthenticatedStudentTestsTestIdSubmittedRouteImport.update({
    id: '/student/tests/$testId/submitted',
    path: '/student/tests/$testId/submitted',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentTestsTestIdStartRoute =
  AuthenticatedStudentTestsTestIdStartRouteImport.update({
    id: '/student/tests/$testId/start',
    path: '/student/tests/$testId/start',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorTestsTestIdResultsRoute =
  AuthenticatedInstructorTestsTestIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedInstructorTestsTestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/instructor/tests/$testId': typeof AuthenticatedInstructorTestsTestIdRouteWithChildren
  '/instructor/tests/$testId/results': typeof AuthenticatedInstructorTestsTestIdResultsRoute
  '/student/tests/$testId/start': typeof AuthenticatedStudentTestsTestIdStartRoute
  '/student/tests/$testId/submitted': typeof AuthenticatedStudentTestsTestIdSubmittedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/instructor/tests/$testId': typeof AuthenticatedInstructorTestsTestIdRouteWithChildren
  '/instructor/tests/$testId/results': typeof AuthenticatedInstructorTestsTestIdResultsRoute
  '/student/tests/$testId/start': typeof AuthenticatedStudentTestsTestIdStartRoute
  '/student/tests/$testId/submitted': typeof AuthenticatedStudentTestsTestIdSubmittedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/instructor/tests/$testId': typeof AuthenticatedInstructorTestsTestIdRouteWithChildren
  '/_authenticated/instructor/tests/$testId/results': typeof AuthenticatedInstructorTestsTestIdResultsRoute
  '/_authenticated/student/tests/$testId/start': typeof AuthenticatedStudentTestsTestIdStartRoute
  '/_authenticated/student/tests/$testId/submitted': typeof AuthenticatedStudentTestsTestIdSubmittedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/instructor/dashboard'
    | '/student/dashboard'
    | '/instructor/tests/$testId'
    | '/instructor/tests/$testId/results'
    | '/student/tests/$testId/start'
    | '/student/tests/$testId/submitted'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/instructor/dashboard'
    | '/student/dashboard'
    | '/instructor/tests/$testId'
    | '/instructor/tests/$testId/results'
    | '/student/tests/$testId/start'
    | '/student/tests/$testId/submitted'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/instructor/dashboard'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/instructor/tests/$testId'
    | '/_authenticated/instructor/tests/$testId/results'
    | '/_authenticated/student/tests/$testId/start'
    | '/_authenticated/student/tests/$testId/submitted'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor/dashboard': {
      id: '/_authenticated/instructor/dashboard'
      path: '/instructor/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof AuthenticatedInstructorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor/tests/$testId': {
      id: '/_authenticated/instructor/tests/$testId'
      path: '/instructor/tests/$testId'
      fullPath: '/instructor/tests/$testId'
      preLoaderRoute: typeof AuthenticatedInstructorTestsTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/tests/$testId/submitted': {
      id: '/_authenticated/student/tests/$testId/submitted'
      path: '/student/tests/$testId/submitted'
      fullPath: '/student/tests/$testId/submitted'
      preLoaderRoute: typeof AuthenticatedStudentTestsTestIdSubmittedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/tests/$testId/start': {
      id: '/_authenticated/student/tests/$testId/start'
      path: '/student/tests/$testId/start'
      fullPath: '/student/tests/$testId/start'
      preLoaderRoute: typeof AuthenticatedStudentTestsTestIdStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor/tests/$testId/results': {
      id: '/_authenticated/instructor/tests/$testId/results'
      path: '/results'
      fullPath: '/instructor/tests/$testId/results'
      preLoaderRoute: typeof AuthenticatedInstructorTestsTestIdResultsRouteImport
      parentRoute: typeof AuthenticatedInstructorTestsTestIdRoute
    }
  }
}

interface AuthenticatedInstructorTestsTestIdRouteChildren {
  AuthenticatedInstructorTestsTestIdResultsRoute: typeof AuthenticatedInstructorTestsTestIdResultsRoute
}

const AuthenticatedInstructorTestsTestIdRouteChildren: AuthenticatedInstructorTestsTestIdRouteChildren =
  {
    AuthenticatedInstructorTestsTestIdResultsRoute:
      AuthenticatedInstructorTestsTestIdResultsRoute,
  }

const AuthenticatedInstructorTestsTestIdRouteWithChildren =
  AuthenticatedInstructorTestsTestIdRoute._addFileChildren(
    AuthenticatedInstructorTestsTestIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInstructorDashboardRoute: typeof AuthenticatedInstructorDashboardRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedInstructorTestsTestIdRoute: typeof AuthenticatedInstructorTestsTestIdRouteWithChildren
  AuthenticatedStudentTestsTestIdStartRoute: typeof AuthenticatedStudentTestsTestIdStartRoute
  AuthenticatedStudentTestsTestIdSubmittedRoute: typeof AuthenticatedStudentTestsTestIdSubmittedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInstructorDashboardRoute: AuthenticatedInstructorDashboardRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedInstructorTestsTestIdRoute:
    AuthenticatedInstructorTestsTestIdRouteWithChildren,
  AuthenticatedStudentTestsTestIdStartRoute:
    AuthenticatedStudentTestsTestIdStartRoute,
  AuthenticatedStudentTestsTestIdSubmittedRoute:
    AuthenticatedStudentTestsTestIdSubmittedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
